name: Deploy Application Stack

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types: [completed]
    branches: [main]

env:
  AWS_REGION: eu-west-1

jobs:
  deploy-application:
    name: Deploy Application Stack
    runs-on: ubuntu-latest
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Validate Application template
      run: |
        aws cloudformation validate-template --template-body file://cloudformation/application-cloudformation.yaml

    - name: Deploy Application Stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/application-cloudformation.yaml \
          --stack-name oauth-service-application \
          --region ${{ env.AWS_REGION }} \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset

    - name: Get application stack outputs
      run: |
        echo "Application Stack outputs:"
        aws cloudformation describe-stacks \
          --stack-name oauth-service-application \
          --region ${{ env.AWS_REGION }} \
          --query 'Stacks[0].Outputs' \
          --output table
