name: Deploy

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repository: webworx-mt/deployment
          event-type: deploy-app
          client-payload: |
            {
              "app_repo": "${{ github.repository }}",
              "app_ref": "${{ github.ref }}",
              "app_sha": "${{ github.sha }}",
              "triggered_by": "${{ github.actor }}"
            }
